### ISSUE TITLE
bower install next line failed

### ISSUE THREAD

**Issue by alindzon** [ricardocanelas/angularjs-typescript-sample-app#1]
C:\development\type>typings install angular --global --save
typings ERR! message Unable to find "angular" ("npm") in the registry.
typings ERR! message However, we found "angular" for 1 other source: "dt"
typings ERR! message You can install these using the "source" option.
typings ERR! message We could use your help adding these typings to the registry
: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/angular/versions/late
st responded with 404, expected it to equal 200

typings ERR! cwd C:\development\type
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\ali
ndzon\AppData\Roaming\npm\node_modules\typings\dist\bin.js" "install" "an
gular" "--global" "--save"
typings ERR! node -v v6.7.0
typings ERR! typings -v 1.4.0

typings ERR! If you need help, you may report this error at:
typings ERR!   https://github.com/typings/typings/issues

**Comment by flythird** [comment]
hello ! 

i discover typescipt and typings
i use nodes and angular

to solve this problem i use the following command : 
typings install angular --global --save --source dt

it works for me. hope this will help you,
